### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by kotuk** [dcarrillo/whatismyip#5]
Hi, can you share your template as example, as i can't find any template example.
Thank you

**Comment by dcarrillo** [comment]
Hi, thank you for your interest in this project.

Currently, a template is just a tmpl file containing something like https://github.com/dcarrillo/whatismyip/blob/f7d0a679c938b46b3bbe85e53737f89c754ebe65/router/templates.go#L4 

For the time being, in order to use CSS, you need to import an external one or just use inline CSS.

I guess you mean the template used at https://ifconfig.es? you can take a look at https://gist.github.com/dcarrillo/67e0e0a85654ab5a57a7589704b6007f
